server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: customer-core-api
          uri: http://core-api-customer:9091
          predicates:
            - Path=/core-api-customer/**
        - id: account-core-api
          uri: http://core-api-account:9091
          predicates:
            - Path=/core-api-account/**